# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2

QUERY_FIELD_NUMBER = 100
query = descriptor.FieldDescriptor(
  name='query', full_name='protobuf_json_test.query', index=0,
  number=100, type=9, cpp_type=9, label=1,
  default_value=unicode("test ext", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
LONG_FIELD_NUMBER = 101
long = descriptor.FieldDescriptor(
  name='long', full_name='protobuf_json_test.long', index=1,
  number=101, type=4, cpp_type=4, label=1,
  default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_TESTMESSAGE_TESTENUM = descriptor.EnumDescriptor(
  name='TestEnum',
  full_name='protobuf_json_test.TestMessage.TestEnum',
  filename='TestEnum',
  values=[
    descriptor.EnumValueDescriptor(
      name='V1', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='V2', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_TESTMESSAGE_NESTEDMSG = descriptor.Descriptor(
  name='NestedMsg',
  full_name='protobuf_json_test.TestMessage.NestedMsg',
  filename='test.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protobuf_json_test.TestMessage.NestedMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='protobuf_json_test.TestMessage.NestedMsg.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='protobuf_json_test.TestMessage.NestedMsg.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTMESSAGE = descriptor.Descriptor(
  name='TestMessage',
  full_name='protobuf_json_test.TestMessage',
  filename='test.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protobuf_json_test.TestMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query', full_name='protobuf_json_test.TestMessage.query', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("test", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flag', full_name='protobuf_json_test.TestMessage.flag', index=2,
      number=3, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test_enum', full_name='protobuf_json_test.TestMessage.test_enum', index=3,
      number=4, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nested_msg', full_name='protobuf_json_test.TestMessage.nested_msg', index=4,
      number=5, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nested_msgs', full_name='protobuf_json_test.TestMessage.nested_msgs', index=5,
      number=6, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rep_int', full_name='protobuf_json_test.TestMessage.rep_int', index=6,
      number=7, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='protobuf_json_test.TestMessage.b', index=7,
      number=8, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bs', full_name='protobuf_json_test.TestMessage.bs', index=8,
      number=9, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _TESTMESSAGE_TESTENUM,
  ],
  options=None)


_TESTMESSAGE.fields_by_name['test_enum'].enum_type = _TESTMESSAGE_TESTENUM
_TESTMESSAGE.fields_by_name['nested_msg'].message_type = _TESTMESSAGE_NESTEDMSG
_TESTMESSAGE.fields_by_name['nested_msgs'].message_type = _TESTMESSAGE_NESTEDMSG

class TestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class NestedMsg(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTMESSAGE_NESTEDMSG
  DESCRIPTOR = _TESTMESSAGE

TestMessage.RegisterExtension(query)
TestMessage.RegisterExtension(long)
